name = "webbios-storefront-engine"
main = "src/index.tsx"
compatibility_date = "2024-03-20"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "webbios_core_db"
database_id = "a8be0324-8183-42ce-884c-527ddaeb5978"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "a97c87f45d53428aac9e66738a9bfc9f"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "webbios-platform"
