export const en = {
  roles: {
    owner: { name: 'Owner', description: 'Full access. Cannot be deleted or revoked.' },
    admin: { name: 'Administrator', description: 'Almost full access. Cannot manage Owner.' },
    staff: { name: 'Staff', description: 'View and process tasks based on assigned permissions.' },
    customer: { name: 'Customer', description: 'Customer account registered from storefront.' }
  },
  permissions: {
    dashboard_view: 'View dashboard',
    settings_view: 'View settings',
    settings_edit: 'Edit settings',
    users_view: 'View users',
    users_manage: 'Manage users',
    media_view: 'View media library',
    media_upload: 'Upload files',
    media_delete: 'Delete files',
    apps_view: 'View apps',
    apps_manage: 'Install/Uninstall apps',
    api_keys_view: 'View API keys',
    api_keys_manage: 'Manage API keys',
    roles_view: 'View roles',
    roles_manage: 'Manage roles',
    permissions_view: 'View permissions',
    permissions_manage: 'Manage permissions',
    menus_view: 'View menus',
    menus_manage: 'Manage menus',
    audit_view: 'View audit logs'
  },
  menus: {
    dashboard: 'Dashboard',
    storefront_category: 'STOREFRONT',
    media: 'Media Library',
    apps_category: 'APP STORE',
    installed_apps: 'Installed Apps',
    apps_store: 'Apps Store',
    system_category: 'SYSTEM',
    system_security: 'Access Control',
    users: 'Users',
    roles: 'Roles',
    permissions: 'Permissions',
    api_keys: 'API Keys',
    system_advanced: 'Advanced',
    menus: 'Menus',
    audit: 'Audit Logs',
    cron_jobs: 'Cron Jobs',
    system_settings: 'Settings',
    settings_system: 'System',
    settings_domains: 'Domains',
    settings_webhooks: 'Webhooks',
    webbios_category: 'WEBBIOS',
    backup_restore: 'Backup & Restore',
    cloudflare_quotas: 'Cloudflare Quotas',
    updates: 'Updates'
  }
};
