export const vi = {
  roles: {
    owner: { name: 'Chủ sở hữu', description: 'Toàn quyền. Không thể xóa hoặc thu hồi quyền.' },
    admin: { name: 'Quản trị viên', description: 'Gần toàn quyền. Không thể quản lý Owner.' },
    staff: { name: 'Nhân viên', description: 'Xem/xử lý tác vụ theo quyền được gán.' },
    customer: { name: 'Khách hàng', description: 'Tài khoản khách hàng đăng ký từ storefront.' }
  },
  permissions: {
    dashboard_view: 'Xem tổng quan',
    settings_view: 'Xem cài đặt',
    settings_edit: 'Sửa cài đặt',
    users_view: 'Xem người dùng',
    users_manage: 'Quản lý người dùng',
    media_view: 'Xem thư viện media',
    media_upload: 'Upload file',
    media_delete: 'Xóa file',
    apps_view: 'Xem ứng dụng',
    apps_manage: 'Cài đặt/Gỡ ứng dụng',
    api_keys_view: 'Xem API keys',
    api_keys_manage: 'Quản lý API keys',
    roles_view: 'Xem vai trò',
    roles_manage: 'Quản lý vai trò',
    permissions_view: 'Xem quyền',
    permissions_manage: 'Quản lý quyền',
    menus_view: 'Xem menu',
    menus_manage: 'Quản lý menu',
    audit_view: 'Xem nhật ký hoạt động'
  },
  menus: {
    dashboard: 'Tổng quan',
    storefront_category: 'KÊNH BÁN HÀNG',
    media: 'Thư viện media',
    apps_category: 'KHO ỨNG DỤNG',
    installed_apps: 'Đã cài đặt',
    apps_store: 'Kho ứng dụng',
    system_category: 'HỆ THỐNG',
    system_security: 'Bảo mật & Phân quyền',
    users: 'Người dùng',
    roles: 'Vai trò',
    permissions: 'Phân quyền',
    api_keys: 'API Keys',
    system_advanced: 'Nâng cao',
    menus: 'Menu',
    audit: 'Nhật ký',
    cron_jobs: 'Cron Jobs',
    system_settings: 'Cài đặt',
    settings_system: 'Hệ thống',
    settings_domains: 'Tên miền',
    settings_webhooks: 'Webhooks',
    webbios_category: 'WEBBIOS',
    backup_restore: 'Sao lưu & Khôi phục',
    cloudflare_quotas: 'Hạn mức Cloudflare',
    updates: 'Cập nhật'
  }
};
