name = "webbios-api"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "webbios_core_db"
database_id = "9239e198-c71e-4ef4-b2e3-abe3eaaf7411"

[vars]
ENVIRONMENT = "production"
INSTANCE_TYPE = "platform"

JWT_SECRET = "super-secret-key-for-now"
