name = "webbios-api-shop9050"
main = "src/index.ts"
compatibility_date = "2024-04-05"
account_id = "acccd6bae01b7e98690322ac773e1cea"

[[d1_databases]]
binding = "DB"
database_name = "webbios_db_shop9050"
database_id = "43d850c2-1fc4-4d74-8f86-ffafd45a7aa9"
