name = "webbios-api"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "webbios_db"
database_id = "fd1e1975-5699-4587-a065-1533c3fafa48"

[vars]
ENVIRONMENT = "production"
INSTANCE_TYPE = "platform"

JWT_SECRET = "super-secret-key-for-now"
CLOUDFLARE_ACCOUNT_ID = "758fa917167175fd22e07a08e402a0c0"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "webbios-platform"

# Service Bindings — App Workers (0ms latency inter-worker calls)
[[services]]
binding = "CRM_API"
service = "wb-api-crm"
