
name = "webbios-api-shop6597"
main = "src/index.ts"
compatibility_date = "2024-03-20"
account_id = "758fa917167175fd22e07a08e402a0c0"

[[d1_databases]]
binding = "DB"
database_name = "webbios_db_shop6597"
database_id = "740839de-c515-46eb-a26e-db83a433ef3c"
